apiVersion: v1
kind: Service
metadata:
  name: dolma-ai-backend-service
  labels:
    app: dolma-ai-backend
spec:
  type: LoadBalancer
  selector:
    app: dolma-ai-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
